repository:
  private: false
  is_template: false

  has_issues: true
  has_wiki: false
  has_downloads: false
  has_projects: true

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

labels:
  - name: bug
    color: '#CC0000'
  - name: feature
    color: '#336699'
  - name: chore
    color: '#f2df8c'
    description: Repoository or code maintenance
  - name: documentation
    color: '#6cb524'
    description: Change in the documentation

collaborators:
  - username: johnmartel
    permission: admin

branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions: {}
      required_status_checks:
        strict: true
        contexts: []
      required_signatures: true
      enforce_admins: null
      restrictions: null
