repository:
  name: .github
  description: Github settings for this organization
  topics: github, configuration
  private: false

  has_issues: true
  has_wiki: false
  has_downloads: false
  has_projects: false

  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

labels:
  - name: bug
    color: '#CC0000'
  - name: feature
    color: '#336699'

collaborators:
  - username: johnmartel
    permission: admin

  - username:
    permission: pull
