repository:
  name: .github
  description: Github settings for this organization
  topics: github, configuration
  private: false
  is_template: false

  has_issues: true
  has_wiki: false
  has_downloads: false
  has_projects: false

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

labels:
  - name: bug
    color: '#CC0000'
  - name: feature
    color: '#336699'

collaborators:
  - username: johnmartel
    permission: admin

branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions: {}
      required_status_checks:
        strict: true
        contexts: ['YAML lint']
      required_signatures: true
      enforce_admins: null
      restrictions: null
